
set(ENABLED_GEMS
    MPS-Asset-Test
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    PhysX
    PrimitiveAssets
    PrefabBuilder
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    props_mps
    character_mps
    kb3d_mps
    landscape_mps
    level_art_mps
    pbr_material_pack_mps
    particlefx_mps
    Terrain
)
